# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.markinfo.dev/
title: Documentation and Projects | Computer Systems Information
email: <a href="mailto:ashinhust.brass@gmail.com">ashinhust.brass@gmail.com</a>
author: Mark Ashinhust
description: >  
  Below contains multiple modules of information in regards to Systems Information and Engineering.
  From programming paradigms to Math and Science, this is everything I learn along the way and want to share with you.
  Feel free to email me with any questions

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/mark-ashinhust-3aa5b9193/
  - title: github
    url: https://github.com/markay12
  - title: email
    url: mailto:ashinhust.brass@gmail.com
